language: python

python:
    - "2.6"
    - "2.7"

sudo: false

env:
    - DJANGO=1.5.12
    - DJANGO=1.6.10

services:
    - memcached

before_install:
    - bash bin/check_signoff.sh
    - pip install -q flake8
    - flake8

install:
    - pip install -q coverage Django==$DJANGO
    - pip install -q -r requirements.txt

script:
    - coverage run test_suite.py

after_success:
    - pip install -q coveralls
    - coveralls
